name: Signup and Login Tests

on:
  workflow_run:
    workflows: ["Build the Project"]
    types:
      - completed

jobs:
  test-signup-login:
    runs-on: ubuntu-latest

    steps:
    # setup
    - name: Checkout code
      uses: actions/checkout@v2

    # setup
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # setup
    - name: Install ODBC Driver for SQL Server
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

    # setup
    - name: Parse and set DB connection environment variables
      run: |
        echo "${{ secrets.DB_CONNECTION }}" > temp_env_file
        while IFS= read -r line; do
          echo "$line" >> $GITHUB_ENV
        done < temp_env_file
        rm temp_env_file

    # setup
    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)

    # setup
    - name: Install backend dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Signup/Login tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        source venv/bin/activate
        pytest backend/tests/test_signup_login.py

  test-frontend-signup-login:
    runs-on: ubuntu-latest
    needs: test-signup-login

    steps:
    # setup
    - name: Checkout code
      uses: actions/checkout@v2

    # setup
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # setup
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
        npm install react-router-dom axios @mui/material @emotion/react @emotion/styled
        npm install --save-dev @babel/preset-env @babel/preset-react babel-jest @babel/plugin-proposal-private-property-in-object

    - name: Run frontend tests for signup/login
      run: |
        cd frontend
        npm run test -- --ci --coverage
