name: User Story 1 - Signup and Login Tests

on:
  workflow_run:
    workflows: ["User Story 0 - Build the Project and Environment"]
    types:
      - completed

jobs:
  test-signup-login:
    uses: ./.github/workflows/user-story-0.yml
    with:
      python-version: '3.8'
      node-version: '18'

    steps:
    - name: Run Signup/Login tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        source venv/bin/activate
        pytest backend/tests/test_signup_login.py

  test-frontend-signup-login:
    needs: test-signup-login
    uses: ./.github/workflows/user-story-0.yml
    with:
      python-version: '3.8'
      node-version: '18'

    steps:
    - name: Run frontend tests for signup/login
      run: |
        cd frontend
        npm run test -- --ci --coverage frontend/src/Components/Sign-Login/SignupPage.test.js
